export const GET_PRODUCTS_LIST_BEGIN = "GET_PRODUCTS_LIST_BEGIN";
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_FAILED = "GET_PRODUCTS_LIST_FAILED";

export const GET_PRODUCTS_SORT_BEGIN = "GET_PRODUCTS_SORT_BEGIN";
export const GET_PRODUCTS_SORT_SUCCESS = "GET_PRODUCTS_SORT_SUCCESS";
export const GET_PRODUCTS_SORT_FAILED = "GET_PRODUCTS_SORT_FAILED";